routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', function () {
//     return view('welcome');
// });

Route::get('/', 'WelcomeController@index')->name('welcome');
Route::post('/filter', 'WelcomeController@filter')->name('filter');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::resource('post', 'PostController');

app/Post.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Post extends Model
{
    //
    protected $fillable = [
        'user_id', 'title', 'topic', 'description',
    ];

    protected $dates = [
        'created_at',
        'updated_at',
        // your other new column
    ];

    public function User()
    {
        return $this->belongsTo('App\User', 'user_id');
    }
}

app/User.php
<?php

namespace App;

use Illuminate\Notifications\Notifiable;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Routing\Controller as BaseController;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Foundation\Auth\Access\AuthorizesRequests;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/PostController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class PostController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        //return "im from index";
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
        return view('post.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
        $input = $request->all();
        Post::create($input);
        return redirect(route('post.create'))->with('message', 'Article Posted Successfully !');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
        $posts = DB::table('posts')->where('user_id', Auth::id())->get();
        return view('post.show', ['posts' => $posts]); 
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
        //return $id;
        $post = Post::findOrFail($id);
        return view('post.edit', compact('post'));
        // return $post;
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
        $post = Post::findOrFail($id);

        $post->update($request->all());
        return redirect(route('post.show', Auth::id()))->with('message', 'Article Updated Successfully !');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
        $post = Post::whereId($id)->delete();
        return redirect(route('post.show', Auth::id()))->with('message', 'Article Deleted Successfully !');
    }
}

app/Http/Controllers/WelcomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Post;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Auth;

class WelcomeController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        //
        $posts = Post::paginate(3);
        return view('welcome', compact('posts'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */

    public function filter(Request $request)
    {
        //
        // $posts = Post::paginate(3);
        $posts = DB::table('posts')->where('topic', $request->topic)->paginate();
        return view('welcome', compact('posts'));
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
	<div class="row justify-content-center">
		<div class="col-md">
			<div class="card">
				<div class="card-header">Dashboard</div>
					<div class="card-body">
						@if (session('status'))
							<div class="alert alert-success" role="alert">
								{{ session('status') }}
							</div>
						@endif
						<div class="row row-cols-1 row-cols-md-3">
							<div class="col mb-4">
								<div class="card">
									<div class="card-body">
										<h5 class="card-title">Create Post</h5>
										<p class="card-text">Create a Post</p>
									<a class="btn btn-primary " href="{{ url('post/create') }}" role="button" style="width: 100%">Create</a>
									</div>
								</div>
							</div>
							<div class="col mb-4">
								<div class="card">
									<div class="card-body">
										<h5 class="card-title">Show, Edit and delete Post</h5>
										<p class="card-text">Show, Edit and delete your post </p>
										<a class="btn btn-primary " href="{{ route('post.show', Auth::id()) }}" role="button" style="width: 100%">Show Post</a>
									</div>
								</div>
							</div>	
						</div>
					</div>
				</div>
			</div>
    	</div>
	</div>
</div>
@endsection

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Blogger</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        <nav class="navbar navbar-expand-md navbar-light navbar-laravel">
            <div class="container">
                <a class="navbar-brand" href="{{ url('/') }}">
                  Home
                </a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <!-- Left Side Of Navbar -->
                    <ul class="navbar-nav mr-auto">

                    </ul>

                    <!-- Right Side Of Navbar -->
                    <ul class="navbar-nav ml-auto">
                        <!-- Authentication Links -->
                        @guest
                            <li class="nav-item">
                                <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                            </li>
                            @if (Route::has('register'))
                                <li class="nav-item">
                                    <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                                </li>
                            @endif
                        @else
                            <li class="nav-item dropdown">
                                <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                                    {{ Auth::user()->name }} <span class="caret"></span>
                                </a>

                                <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                                    <a class="dropdown-item" href="{{ route('logout') }}"
                                       onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                        {{ __('Logout') }}
                                    </a>

                                    <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                        @csrf
                                    </form>
                                </div>
                            </li>
                        @endguest
                    </ul>
                </div>
            </div>
        </nav>

        <main class="py-4">
            @yield('content')
        </main>
    </div>
</body>
</html>

resources/views/post/create.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    @if(session()->has('message'))
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="zmdi zmdi-close"></i>
        </button>
        <strong>
            <i class="zmdi zmdi-check"></i> Success!</strong> {{ session()->get('message') }}
      </div>
    @endif
    <form action="{{ url('post') }}" method="POST">
      @csrf
      <input type="hidden" value="{{ Auth::id() }}" class="form-control" id="user_id" name="user_id" >
      <div class="form-group">
        <label for="title">Title</label>
        <input type="text" class="form-control" id="title" placeholder="Enter title" name="title" autocomplete="off" required>
      </div>
      <div class="form-group">
        <label for="title">Select Topic</label>
        <select class="form-control"  name="topic" required> 
          <label for="exampleInputEmail1">Title</label>
          <option>Information Technology</option>
          <option>Finance</option>
          <option>Sports</option>
          <option>Stock Market</option>
          <option>Covid - 19</option>
          <option>Banking Industry</option>
          <option>Social Media</option>
          <option>Mobile Phones</option>
          <option>Ministry of External Affairs</option>
        </select>
      </div>
      <div class="form-group">
        <label for="exampleFormControlTextarea1">Description</label>
        <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="description" required></textarea>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
      <a class="btn btn-primary " href="{{ url('/home') }}" role="button" >Go back</a>
    </form>
  </div>
@endsection

resources/views/post/delete.blade.php
@extends('layouts.app')

@section('content')
    Delete a Post
@endsection

resources/views/post/edit.blade.php
@extends('layouts.app')

@section('content')
  <div class="container">
    @if(session()->has('message'))
      <div class="alert alert-success alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
            <i class="zmdi zmdi-close"></i>
        </button>
        <strong>
            <i class="zmdi zmdi-check"></i> Success!</strong> {{ session()->get('message') }}
      </div>
    @endif
    <form action="{{ route('post.update', $post->id) }}" method="post">

      {{ csrf_field() }}

      <input type="hidden" name="_method" value="PUT">
      <input type="hidden" value="{{ Auth::id() }}" class="form-control" id="user_id" name="user_id" >
      <div class="form-group">
        <label for="title">Title</label>
      <input type="text" class="form-control" id="title" placeholder="Enter title" value="{{ $post->title, $post->id }}" name="title" autocomplete="off" required>
      </div>
      <div class="form-group">
        <label for="title">Select Topic</label>
        <select class="form-control"  name="topic" required> 
          <label for="exampleInputEmail1">Title</label>
          <option>Information Technology</option>
          <option>Finance</option>
          <option>Sports</option>
          <option>Stock Market</option>
          <option>Covid - 19</option>
          <option>Banking Industry</option>
          <option>Social Media</option>
          <option>Mobile Phones</option>
          <option>Ministry of External Affairs</option>
        </select>
      </div>
      <div class="form-group">
        <label for="exampleFormControlTextarea1">Description</label>
      <textarea class="form-control" id="exampleFormControlTextarea1" rows="3" name="description" required>{{ $post->description }}</textarea>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>
      <a class="btn btn-primary " href="{{ url('/post') }}" role="button" >Go back</a>
    </form>
  </div>
@endsection

resources/views/post/index.blade.php
@extends('layout.app')

@section('content')
    <div>qwertyuiop</div>
@endsection

resources/views/post/show.blade.php
@extends('layouts.app')

@section('content')

<div class="container">
<div class="row justify-content-center">
    <div class="col-md">
        <div class="card">
            <div class="card-header">Your Posts <a class="btn btn-primary" href="{{ url('/home') }}" role="button" >Go back</a></div>
                <div class="card-body">
                    @if(session()->has('message'))
                        <div class="alert alert-success alert-dismissible" role="alert">
                            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                                <i class="zmdi zmdi-close"></i>
                            </button>
                            <strong>
                                <i class="zmdi zmdi-check"></i> Success!</strong> {{ session()->get('message') }}
                        </div>
                        @endif
                    
                    @foreach ($posts as $post)
                        <div class="row row-cols-1 row-cols-md-3">
                        <div class="col mb-4">
                            <div class="card">
                                <div class="card-body">
                                    <h5 class="card-title">{{ $post->title }}</h5>
                                    <p class="card-text"><small class="text-muted">Created {{ \Carbon\Carbon::parse($post->created_at)->diffForHumans() }}</small></p>
                                    <p class="card-text">{{ $post->topic }}</p>
                                    <p class="card-text">{{ $post->description }}</p>
                                    <p class="card-text"><small class="text-muted">Updated {{ \Carbon\Carbon::parse($post->updated_at)->diffForHumans() }}</small></p>
                                    <form method="post" action="{{ route('post.destroy', $post->id) }}">
                                        {{ csrf_field() }}
                                        <input type="hidden" name="_method" value="DELETE">
                                        <a class="btn btn-primary " href="{{ route('post.edit', $post->id) }}" role="button" >Edit</a>
                                        <input class="btn btn-danger" type="submit" value="DELETE" ;>
                                    </form>
                                </div>
                            </div>
                        </div>
                    </div>
                    @endforeach
                    
                </div>
            </div>
        </div>
    </div>    
</div>


@endsection